### ISSUE TITLE
[Issue] Cell Detection Performance.

### ISSUE THREAD

**Issue by k920049** [poloclub/tsr-convstem#1]
Thanks for your finding on table structure recognition.

According to the paper, there are numerous experiments on measuring the performance for recognizing the structure of a table but I can't find any cell detection performance metrics (AP50, AP(50:95:05). ...). Can you share the results?

**Comment by ShengYun-Peng** [comment]
Hey @k920049, thanks for your interest in our work! As mentioned in the paper, our work mainly focused on the table structure recognition defined in the HTML format. We plan to add more downstream tasks in the future including cell detection. Stay tuned for our new paper coming soon.
