### ISSUE TITLE
After the first Epoch ends, an error "torch.cuda.OutOfMemoryError: CUDA out of memory" is reported. 

### ISSUE THREAD

**Issue by Kinsue** [poloclub/tsr-convstem#4]
In my training configuration, training can be done on a single 4090 by reducing the batch size. However, after the first Epoch ends, an "torch.cuda.OutOfMemoryError: CUDA out of memory" error occurs. 
**May I ask on what device is your team training? Should I continue to reduce the batch size?**

**Comment by ShengYun-Peng** [comment]
Hi @Kinsue, perhaps reducing the batch size would help mitigate the issue. For this paper, the model was trained on A100 80G. I recommend trying out our latest work, namely UniTable, at https://github.com/poloclub/unitable. We have provided a tiny portion (20 samples) of PubTabNet for some toy pretraining and finetuning. Meanwhile, you can also control the [max_seq_len](https://github.com/poloclub/unitable/blob/8ea3ada9f4d1676d6d952b43d234534ef05975e9/configs/trainer/table.yaml#L9) and [img_size](https://github.com/poloclub/unitable/blob/8ea3ada9f4d1676d6d952b43d234534ef05975e9/configs/trainer/table.yaml#L8) to lower the GPU memory usage.

**Comment by Kinsue** [comment]
Thank you very much for your reply. I am happy to try out your latest work and appreciate your contributions.
